### ISSUE TITLE
FrozenError: can't modify frozen String

### ISSUE THREAD

**Issue by madleech** [socketry/http-accept#12]
I'm getting a `FrozenError` when trying to `fail! :bad_request` in a Utopia controller with `respond.with_json` enabled.

Stack trace:
```
FrozenError: can't modify frozen String
	/home/michael/.rvm/gems/ruby-2.6.3/gems/http-accept-1.7.0/lib/http/accept/media_types.rb:117:in `strip!'
	/home/michael/.rvm/gems/ruby-2.6.3/gems/http-accept-1.7.0/lib/http/accept/media_types.rb:117:in `browser_preferred_media_types'
	/home/michael/.rvm/gems/ruby-2.6.3/gems/utopia-2.9.3/lib/utopia/controller/respond.rb:142:in `call'
	/home/michael/.rvm/gems/ruby-2.6.3/gems/utopia-2.9.3/lib/utopia/controller/respond.rb:161:in `response_for'
	/home/michael/.rvm/gems/ruby-2.6.3/gems/utopia-2.9.3/lib/utopia/controller/respond.rb:175:in `process!'
	/home/michael/.rvm/gems/ruby-2.6.3/gems/utopia-2.9.3/lib/utopia/controller.rb:143:in `invoke_controllers'
	/home/michael/.rvm/gems/ruby-2.6.3/gems/utopia-2.9.3/lib/utopia/controller.rb:161:in `call'
```

`accept_content_types` is set to `text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3`.

Example Utopia 2.9.3 test case:
```rb
prepend Respond, Actions
respond.with_json

on 'foo' do
	fail! :bad_request
end
```

**Comment by ioquatix** [comment]
oh crap, I thought I fixed all of these.

**Comment by ioquatix** [comment]
Okay, it turns out utopia is still using `~> 1.6` which had some issues with frozen headers.

So, I'm updating it to use `~> 2.1` which doesn't use `strip!`.

**Comment by madleech** [comment]
Thanks, working great.
